
# -*- coding: utf-8 -*-
# Configuration file for grimoireng_cloud.py

from collections import OrderedDict

# elasticsearch = None
elasticsearch = [
    "https://789ba13a7edced40de95ef091ac591d3.us-east-1.aws.found.io:9243",
    "scm"
]

PortSpectrum = 3307
PortAtari = 3308
dashboards = OrderedDict ([
    ("ElasticSearch", {"scmdb": "quan_cvsanaly_elastic_6863",
                       "scrdb": None,
                       "shdb": "quan_sortinghat_elastic_6863",
                       "prjdb": None,
                       "port": PortSpectrum}),
    ("Kubernetes", {"scmdb": "lcanas_cvsanaly_kubernetes_oscon2015",
                    "scrdb": None,
                    "shdb": "lcanas_sortinghat_kubernetes_oscon2015",
                    "prjdb": None,
                    "port": PortSpectrum}),
    ("Docker", {"scmdb": "quan_cvsanaly_docker_6753",
                "scrdb": None,
                "shdb": "quan_sortinghat_docker_6753",
                "prjdb": None,
                "port": PortSpectrum}),
    ("Puppet", {"scmdb": "puppet_2015q3_cvsanaly",
                "scrdb": None,
                "shdb": "puppet_2015q3_sortinghat",
                "prjdb": None,
                "port": PortSpectrum}),
    ("Midonet", {"scmdb": "cp_cvsanaly_midokura",
                 "scrdb": "cp_gerrit_midokura",
                 "shdb": "cp_sortinghat_midokura",
                 "prjdb": None,
                 "port": PortSpectrum}),
    ("OpenStack", {"scmdb": "amartin_cvsanaly_openstack_sh",
                   "scrdb": "amartin_bicho_gerrit_openstack_sh",
                   "shdb": "amartin_sortinghat_openstack_sh",
                   "prjdb": "amartin_projects_openstack_sh_2",
                   "port": PortAtari}),
    ("MediaWiki", {"scmdb": "acs_cvsanaly_mediawiki_5300",
                   "scrdb": "dic_gerrit_mediawiki_5829",
                   "shdb": "acs_sortinghat_mediawiki_5879",
                   "prjdb": None,
                   "port": PortAtari}),
    ("CloudStack", {"scmdb": "sduenas_cvsanaly_cloudstack_3246",
                    "scrdb": None,
                    "shdb": "amartin_sortinghat_cloudstack",
                    "prjdb": None,
                    "port": PortAtari}),
    ("OPNFV", {"scmdb": "dpose_cvsanaly_linux_foundation_6219_and_6222",
               "scrdb": "dpose_gerrit_linux_foundation_6219_and_6222",
               "shdb": "dpose_sortinghat_linux_foundation_6219_and_6222",
               "prjdb": None,
               "port": PortSpectrum}),
#    ("Eclipse", {"scmdb": "cp_cvsanaly_Eclipse_5986",
#                 "scrdb": "cp_gerrit_Eclipse_5467",
#                 "shdb": "cp_sortinghat_Eclipse_5680",
#                 "prjdb": "cp_projects_Eclipse_5680",
#                 "port": PortSpectrum}),
    ("Eclipse", {"scmdb": "cp_cvsanaly_Eclipse_5986_copy",
                 "scrdb": "cp_gerrit_Eclipse_5467_copy",
                 "shdb": "cp_sortinghat_Eclipse_5680_copy",
                 "prjdb": "cp_gerrit_Eclipse_5467_copy",
                 "port": PortSpectrum}),
    ("ownCloud", {"scmdb": "cp_cvsanaly_ownCloud2",
                  "scrdb": None,
                  "shdb": "cp_sortinghat_ownCloud",
                  "prjdb": None,
                  "port": PortSpectrum}),
    ("FirefoxOS", {"scmdb": "jalonso_cvsanaly_mozillab2g",
                   "scrdb": None,
                   "shdb": "jalonso_sortinghat_mozillab2g",
                   "prjdb": None,
                   "port": PortSpectrum}),
    ("Akanda", {"scmdb": "jalonso_cvsanaly_akanda_7117",
                "scrdb": "jalonso_bicho_gerrit_akanda_7146",
                "shdb": "jalonso_sortinghat_akanda_7117",
                "prjdb": None,
                "port": PortSpectrum}),
    ("FreeIPA",
     {"scmdb": "dpose_cvsanaly_freeipa_6238",
      "scrdb": None,
      "shdb": "dpose_sortinghat_freeipa_6238",
      "prjdb": "dpose_freeipa_6238",
      "port": PortSpectrum}),
    ("GlusterFS",
     {"scmdb": "acs_cvsanaly_redhat_glusterfs_2437",
      "scrdb": None,
      "shdb": "amartin_sortinghat_glusterfs",
      "prjdb": None,
      "port": PortSpectrum}),
    ("ManageIQ",
     {"scmdb": "cp_cvsanaly_manageiq",
      "scrdb": None,
      "shdb": "cp_sortinghat_manageiq",
      "prjdb": None,
      "port": PortSpectrum}),
    ("OVirt",
     {"scmdb": "acs_cvsanaly_redhat_ovirt_2437",
      "scrdb": "dic_gerrit_redhat_ovirt_5833",
      "shdb": "acs_sortinghat_redhat_ovirt_5641",
      "prjdb": None,
      "port": PortSpectrum}),
    ("RDO",
     {"scmdb": "amartin_cvsanaly_redhat_rdo_2439",
      "scrdb": None,
      "shdb": "amartin_sortinghat_redhat_rdo",
      "prjdb": None,
      "port": PortSpectrum}),
    ("Ceph",
     {"scmdb": "amartin_cvsanaly_ceph",
      "scrdb": None,
      "shdb": "amartin_sortinghat_ceph",
      "prjdb": None,
      "port": PortSpectrum})
])
